

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainfall
  namespace: default
  labels:
    app: rainfall
spec:
  selector:
    matchLabels:
      app: rainfall
  replicas: 1
  template:
    metadata:
      labels:
        app: rainfall
    spec:
      containers:
      - name: rainfall
        image: ruum/rainfall:latest
        env:
        - name: LOCNAME
          valueFrom:
            configMapKeyRef:
              name: rainfall
              key: LOCNAME
        - name: HOSTURL
          valueFrom:
            configMapKeyRef:
              name: rainfall
              key: HOSTURL
        imagePullPolicy: Always
        ports:
        - containerPort: 8080